services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=room_booking_service'
      - 'MYSQL_USER=app'
      - 'MYSQL_PASSWORD=password'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
